name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Vite GitHub Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.5.0
        with:
          public_base_path: /
          build_path: ./dist
          install_phase_node_env: dev
          build_phase_node_env: production
          package_manager: npm
          artifact_name: github-pages
          debug_mode: false
          working_path: ./
